"""init

Revision ID: 0d9ed7a4bf00
Revises: 
Create Date: 2025-03-27 15:38:37.834619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9ed7a4bf00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('eid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ecid', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('start_signup_time', sa.Integer(), nullable=True),
    sa.Column('end_signup_time', sa.Integer(), nullable=True),
    sa.Column('start_signin_time', sa.Integer(), nullable=True),
    sa.Column('end_signin_time', sa.Integer(), nullable=True),
    sa.Column('signin_code', sa.String(length=16), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=36), nullable=True),
    sa.Column('first_publish', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('eid')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_eid'), ['eid'], unique=False)

    op.create_table('event_category',
    sa.Column('ecid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ecid')
    )
    with op.batch_alter_table('event_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_category_ecid'), ['ecid'], unique=False)

    op.create_table('news',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('first_publish', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_nid'), ['nid'], unique=False)

    op.create_table('regesiter',
    sa.Column('seid', sa.String(length=24), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=True),
    sa.Column('nick', sa.String(length=32), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seid'),
    sa.UniqueConstraint('openid'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('regesiter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regesiter_seid'), ['seid'], unique=False)

    op.create_table('roles',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rid'),
    sa.UniqueConstraint('role_name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_rid'), ['rid'], unique=False)

    op.create_table('users',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('nick', sa.String(length=32), nullable=True),
    sa.Column('passwd', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.Integer(), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('openid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_uid'), ['uid'], unique=False)

    op.create_table('admin_roles',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('admins',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('aid'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_aid'), ['aid'], unique=False)

    op.create_table('participation',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=True),
    sa.Column('eid', sa.Integer(), nullable=True),
    sa.Column('signup_time', sa.Integer(), nullable=True),
    sa.Column('signup_ip', sa.String(length=64), nullable=True),
    sa.Column('signin_time', sa.Integer(), nullable=True),
    sa.Column('signin_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['event.eid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('uid', 'eid', name='unique_eid_uid')
    )
    op.create_table('user_event',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('participation_time', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['event.eid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'eid')
    )
    with op.batch_alter_table('user_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_event_place'), ['place'], unique=False)

    op.create_table('user_role_association',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'rid')
    )
    op.create_table('user_roles',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('admin_role_association',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['admins.aid'], ),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ),
    sa.PrimaryKeyConstraint('aid', 'rid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_role_association')
    op.drop_table('user_roles')
    op.drop_table('user_role_association')
    with op.batch_alter_table('user_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_event_place'))

    op.drop_table('user_event')
    op.drop_table('participation')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_aid'))

    op.drop_table('admins')
    op.drop_table('admin_roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uid'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_rid'))

    op.drop_table('roles')
    with op.batch_alter_table('regesiter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regesiter_seid'))

    op.drop_table('regesiter')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_nid'))

    op.drop_table('news')
    with op.batch_alter_table('event_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_category_ecid'))

    op.drop_table('event_category')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_eid'))

    op.drop_table('event')
    # ### end Alembic commands ###
