"""user mngt

Revision ID: 3a90aea8e4a2
Revises: 8e5c53de3166
Create Date: 2025-03-27 10:25:58.068375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a90aea8e4a2'
down_revision: Union[str, None] = '8e5c53de3166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.drop_column('signin_location')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['rid'])

    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signin_location', sa.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'event_category', ['ecid'], ['ecid'])

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['rid'])

    # ### end Alembic commands ###
