"""initial schema

Revision ID: 8e79605fd37a
Revises: 
Create Date: 2025-08-26 15:22:14.690825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e79605fd37a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_time_slot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_name', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=50), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_time_slot_id'), 'interview_time_slot', ['id'], unique=False)
    op.create_table('member',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('render', sa.Boolean(), nullable=True),
    sa.Column('major_id', sa.String(length=24), nullable=True),
    sa.Column('major_name', sa.String(length=24), nullable=True),
    sa.Column('college_id', sa.String(length=24), nullable=True),
    sa.Column('college_name', sa.String(length=24), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('bank_card', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_holder', sa.String(length=24), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('evaluation_count', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('wechat', sa.String(length=50), nullable=True),
    sa.Column('qq', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_member_uid'), 'member', ['uid'], unique=True)
    op.create_table('recruitment',
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('render', sa.Boolean(), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('major_id', sa.String(length=24), nullable=True),
    sa.Column('major_name', sa.String(length=24), nullable=True),
    sa.Column('college_id', sa.String(length=24), nullable=True),
    sa.Column('college_name', sa.String(length=24), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.Column('office_department_willing', sa.Integer(), nullable=True),
    sa.Column('competition_department_willing', sa.Integer(), nullable=True),
    sa.Column('activity_department_willing', sa.Integer(), nullable=True),
    sa.Column('research_department_willing', sa.Integer(), nullable=True),
    sa.Column('if_agree_to_be_reassigned', sa.Boolean(), nullable=True),
    sa.Column('if_be_member', sa.Boolean(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('skill', sa.Text(), nullable=True),
    sa.Column('evaluation_status', sa.String(length=20), nullable=True),
    sa.Column('evaluation_time', sa.DateTime(), nullable=True),
    sa.Column('evaluator_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_department', sa.String(length=50), nullable=True),
    sa.Column('interview_status', sa.String(length=20), nullable=True),
    sa.Column('interview_time_slots', sa.Text(), nullable=True),
    sa.Column('interview_completed', sa.Boolean(), nullable=True),
    sa.Column('first_round_passed', sa.Boolean(), nullable=True),
    sa.Column('second_round_passed', sa.Boolean(), nullable=True),
    sa.Column('is_admitted', sa.Boolean(), nullable=True),
    sa.Column('admission_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_recruitment_uid'), 'recruitment', ['uid'], unique=True)
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('evaluator_id', sa.String(length=36), nullable=False),
    sa.Column('evaluator_name', sa.String(length=50), nullable=False),
    sa.Column('evaluation_comment', sa.Text(), nullable=False),
    sa.Column('evaluation_time', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('technical_skills', sa.Float(), nullable=True),
    sa.Column('communication_skills', sa.Float(), nullable=True),
    sa.Column('problem_solving', sa.Float(), nullable=True),
    sa.Column('teamwork', sa.Float(), nullable=True),
    sa.Column('learning_ability', sa.Float(), nullable=True),
    sa.Column('motivation', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('recommended_department', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['recruitment.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_id'), 'evaluation', ['id'], unique=False)
    op.create_table('interview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('interview_date', sa.DateTime(), nullable=False),
    sa.Column('interview_format', sa.String(length=20), nullable=False),
    sa.Column('interview_duration', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('technical_skills', sa.Float(), nullable=True),
    sa.Column('communication_skills', sa.Float(), nullable=True),
    sa.Column('problem_solving', sa.Float(), nullable=True),
    sa.Column('teamwork', sa.Float(), nullable=True),
    sa.Column('learning_ability', sa.Float(), nullable=True),
    sa.Column('motivation', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('technical_questions', sa.Text(), nullable=True),
    sa.Column('behavioral_questions', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('recommended_department', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['time_slot_id'], ['interview_time_slot.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['recruitment.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_id'), 'interview', ['id'], unique=False)
    op.create_index(op.f('ix_interview_uid'), 'interview', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_uid'), table_name='interview')
    op.drop_index(op.f('ix_interview_id'), table_name='interview')
    op.drop_table('interview')
    op.drop_index(op.f('ix_evaluation_id'), table_name='evaluation')
    op.drop_table('evaluation')
    op.drop_index(op.f('ix_recruitment_uid'), table_name='recruitment')
    op.drop_table('recruitment')
    op.drop_index(op.f('ix_member_uid'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_interview_time_slot_id'), table_name='interview_time_slot')
    op.drop_table('interview_time_slot')
    # ### end Alembic commands ###
