"""init

Revision ID: 916dd2c9bb4e
Revises: 
Create Date: 2024-10-15 12:27:43.428357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916dd2c9bb4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('eid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=36), nullable=True),
    sa.Column('first_publish', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('eid')
    )
    op.create_index(op.f('ix_event_eid'), 'event', ['eid'], unique=False)
    op.create_table('news',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('first_publish', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_news_nid'), 'news', ['nid'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('nick', sa.String(length=32), nullable=True),
    sa.Column('passwd', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_news_nid'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_event_eid'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
