"""add image and category

Revision ID: 96b3920657a1
Revises: 916dd2c9bb4e
Create Date: 2024-10-29 22:50:28.298571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b3920657a1'
down_revision: Union[str, None] = '916dd2c9bb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('event', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'category')
    op.drop_column('news', 'image')
    op.drop_column('event', 'category')
    op.drop_column('event', 'image')
    # ### end Alembic commands ###
