"""add new tables

Revision ID: aff20e1b6e46
Revises: 96b3920657a1
Create Date: 2024-11-17 19:54:49.970384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff20e1b6e46'
down_revision: Union[str, None] = '96b3920657a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participation',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('signup_time', sa.Integer(), nullable=True),
    sa.Column('signup_ip', sa.String(length=64), nullable=True),
    sa.Column('signin_time', sa.Integer(), nullable=True),
    sa.Column('signin_ip', sa.String(length=64), nullable=True),
    sa.Column('signin_location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'eid')
    )
    op.create_index(op.f('ix_participation_eid'), 'participation', ['eid'], unique=False)
    op.create_index(op.f('ix_participation_uid'), 'participation', ['uid'], unique=False)
    op.create_table('roles',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_index(op.f('ix_roles_rid'), 'roles', ['rid'], unique=False)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('admin_roles',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rid'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('admins',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.rid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_admins_aid'), 'admins', ['aid'], unique=False)
    op.create_table('user_roles',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rid'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('admin_role_association',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['admins.aid'], ),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ),
    sa.PrimaryKeyConstraint('aid', 'rid')
    )
    op.create_table('user_event',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('participation_time', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['event.eid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'eid')
    )
    op.create_index(op.f('ix_user_event_place'), 'user_event', ['place'], unique=False)
    op.create_table('user_role_association',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['roles.rid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'rid')
    )
    op.add_column('event', sa.Column('start_signup_time', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('end_signup_time', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('start_signin_time', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('end_signin_time', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('signin_location', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['rid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_column('event', 'signin_location')
    op.drop_column('event', 'end_signin_time')
    op.drop_column('event', 'start_signin_time')
    op.drop_column('event', 'end_signup_time')
    op.drop_column('event', 'start_signup_time')
    op.drop_table('user_role_association')
    op.drop_index(op.f('ix_user_event_place'), table_name='user_event')
    op.drop_table('user_event')
    op.drop_table('admin_role_association')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_admins_aid'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('admin_roles')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_rid'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_participation_uid'), table_name='participation')
    op.drop_index(op.f('ix_participation_eid'), table_name='participation')
    op.drop_table('participation')
    # ### end Alembic commands ###
